# Generated by Django 6.1 on 2026-08-17 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=60)),
                ('url', models.URLField()),
                ('check_interval', models.PositiveSmallIntegerField(default=300)),
                ('api_status', models.CharField(choices=[('UP', 'Online'), ('DOWN', 'Offline'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=7)),
                ('timeout_count', models.PositiveSmallIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_response', models.CharField(max_length=30)),
                ('status_code', models.PositiveSmallIntegerField(null=True)),
                ('response_time', models.PositiveSmallIntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='monitoring.api')),
            ],
        ),
    ]
