# Generated by Django 6.1 on 2026-09-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='check_interval',
        ),
    ]
