name: Pipeline

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
      CELERY_BROKER_URL: "redis://localhost:6379/0"
      REDIS_CACHE_URL: "redis://localhost:6379/1"

    steps:
      - name: Copiar repositório
        uses: actions/checkout@v5

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar dependências
        run: poetry install --no-root

      - name: Executar testes
        run: poetry run python manage.py test